In [1]:
from arnoldi import arnoldi
import numpy as np
np.set_printoptions(precision=1)

In [2]:
A = np.random.rand(5,5)
B = A.T.dot(A)

In [3]:
V, H = arnoldi(A, 4)
print(np.around(H, decimals=1))

[[ 1.2  1.1  0.9  0.5]
 [ 1.6  1.1 -0.   0.7]
 [ 0.   0.9  0.1  0. ]
 [ 0.   0.   0.3 -0.2]]


In [4]:
V, H = arnoldi(B, 4)
print(np.around(H, decimals=1))

[[ 5.6  3.3  0.  -0. ]
 [ 3.3  2.4  0.3 -0. ]
 [ 0.   0.3  0.4  0.2]
 [ 0.   0.   0.2  0.5]]


In [5]:
V.T.dot(V)

array([[ 1.0e+00, -5.6e-16,  9.7e-16, -1.6e-15],
       [-5.6e-16,  1.0e+00,  2.5e-15, -6.4e-15],
       [ 9.7e-16,  2.5e-15,  1.0e+00,  2.9e-16],
       [-1.6e-15, -6.4e-15,  2.9e-16,  1.0e+00]])

In [6]:
A = np.array([[1,0,0],[2,1,0],[0,3,1]])